export const businessName = "대전톰바";
export const area = "대전시 유성구";
export const detailAddress = "봉명동 445-13번지 GS편의점 2층 톰바";
export const phoneDisplay = "010-5955-6174";
export const phoneHref = "tel:010-5955-6174";
export const managerName = "유진실장";
export const kakaoOpenChatHref = "https://open.kakao.com/o/sONG5ODi";
export const siteUrl = "https://www.daejeonhopa.com";
export const fullAddress = `${area} ${detailAddress}`;
const mapQuery = encodeURIComponent(fullAddress);
export const mapEmbedSrc = `https://www.google.com/maps?q=${mapQuery}&output=embed`;
export const mapDirectionsHref = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
